### ISSUE TITLE
More info on K3/AH4 interface?

### ISSUE THREAD

**Issue by bgelb** [doitnowlabs/K3-AH4-Interface#1]
Hi - I am very interested in your design for the K3/AH4 interface. Are there any additional details about its design that you can share?

Thanks!

Ben, N1VF

**Comment by doitnowlabs** [comment]
Hi Ben, I'm so sorry I did not see your message until now. I don't often log into github under this account- I always try to respond when people message me, so my apologies. Recently I've had a few people email me about this project, and while I personally don't remember many of the details, I managed to dig up all the old code and schematics. As far as I remember, this was the most recent revision I made before calling it "good enough" and moving on to new projects. All files should now be uploaded to the github page. Hope this helps.

Ben KC9ROI
